``

diff --git a/other/setup-rpi b/other/setup-rpi
--- a/other/setup-rpi
+++ b/other/setup-rpi
@@ -41,8 +41,25 @@ fi
 
 
 ## Setup updater
-sed 's/exit 0//g' /etc/rc.local
 cat >> /etc/rc.local << EOF
+#!/bin/sh -e
+#
+# rc.local
+#
+# This script is executed at the end of each multiuser runlevel.
+# Make sure that the script will "exit 0" on success or any other
+# value on error.
+#
+# In order to enable or disable this script just change the execution
+# bits.
+#
+# By default this script does nothing.
+
+# Print the IP address
+_IP=$(hostname -I) || true
+if [ "$_IP" ]; then
+  printf "My IP address is %s\n" "$_IP"
+fi
 sleep 5
 if ping -c 5 8.8.8.8
 then
